default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  url: <%= ENV['DATABASE_URL'] %>
  # password: <%= ENV["POSTGRES_PASSWORD"] %>

  # 本番用
  # adapter: postgresql
  # encoding: unicode
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: <%= ENV['POSTGRES_HOST'] %>
  # username: <%= ENV['POSTGRES_USER'] %>
  # password: <%= ENV['POSTGRES_PASSWORD'] %>
  # database: <%= ENV['POSTGRES_DB'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default